spring:
  application:
    name: graphql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=problemz
    username: postgres
    password: postgres